Improves record-value manipulation
cortezaproject/corteza-server pull request #197
Opened 2021-06-07 12:24 UTC by vicpatel

This will fix WF issue for accessing record's value via selectors & gval expressions

Please take a look.

2021-06-11 15:05 UTC, tjerman reviewed
This seems fine to me. I'll take another closer look before we merge it tho (not before next week!)

2021-06-11 15:05 UTC, tjerman commented on compose/automation/expr_types.go
> +
remove empty line

2021-06-15 07:44 UTC, tjerman requested changes
In addition to my comments, can you please add some additional tests to cover cases with missing values?

2021-06-15 07:44 UTC, tjerman commented on compose/automation/expr_types.go
> +			}
`nil` can be a bit tricky when working with `interface{}`.
I would prefer to see something in the lines of https://github.com/cortezaproject/corteza-server/blob/2021.6.x-fix-wf-copy-record/pkg/expr/func_generic.go#L42 with some additional tests to cover this specific execution path.
You can copy-paste that function into the `compose/automation` package.

Ref: https://yourbasic.org/golang/gotcha-why-nil-error-not-equal-nil/

2021-06-15 07:44 UTC, tjerman commented on compose/automation/expr_types.go
> +					}
I would prefer to see these comments explaining the booleans below the `case bool:` line; all together

2021-06-15 15:15 UTC, tjerman reviewed
What is that number for? Other then that, lgtm, merge

2021-06-15 15:15 UTC, tjerman commented on compose/automation/expr_types_test.go
> +			// &types.RecordValue{Name: "bools", Value: "false", Place: 1}, 9879201458
?

2021-06-16 06:26 UTC, vicpatel commented on compose/automation/expr_types_test.go
> +			// &types.RecordValue{Name: "bools", Value: "false", Place: 1}, 9879201458
My bad, will remove it!

2021-06-16 07:04 UTC, closed without merging