Adds admin API for user session enhancement
cortezaproject/corteza-server pull request #210
Opened 2021-06-29 23:03 UTC by vicpatel

- log-out users from all sessions
- unauthorize all auth clients

Please take a look.

2021-06-30 05:22 UTC, darh requested changes

2021-06-30 05:22 UTC, darh commented on auth/handlers/handle_sessions.go
> +		if err = h.SessionManager.DeleteByID(req.Context(), s.id); err != nil {
how about if we just use DeleteByUserID() instead of loading+looping+deleting-each-one?

2021-06-30 05:22 UTC, darh commented on auth/handlers/handle_authorized-clients.go
> +		if err = h.TokenService.DeleteByID(req.Context(), clientID); err != nil {
how about if we just use DeleteByUserID() instead of loading+looping+deleting-each-one?

2021-07-06 05:49 UTC, vicpatel commented
> well... `DELETE .../logout` does not make much sense. How could this be improved?



> well... `DELETE .../logout` does not make much sense. How could this be improved?

Yes, DELETE `../authentication`

2021-07-06 05:53 UTC, darh commented
How about `.../sessions`? This way we are future-proof if/when we split this to 2 endpoints (one for sessions, one for tokens) as we discussed.

2021-07-06 05:54 UTC, darh commented
How about `DELETE .../sessions`? This way we'll be future-proof when we decide to break this into two endpoints (one for sessions, other for oa2 tokens)?

2021-07-06 15:45 UTC, closed without merging